elasticsearch:
  image: elasticsearch:1.7

mongo:
  image: mongo:3.1

server:
  #build: server
  image: etki/graylog-server
  environment:
    GRAYLOG2_MONGODB_URI: mongodb://mongo:27017/test
    GRAYLOG2_ELASTICSEARCH_HOSTS: elasticsearch:9300
    GRAYLOG2_ELASTICSEARCH_CLUSTER_NAME: elasticsearch
  links:
    - mongo:mongo
    - elasticsearch:elasticsearch

web_interface:
  #build: web-interface
  image: etki/graylog-web-interface
  links:
    - server:server
  environment:
    GRAYLOG2_SERVER_URI: http://server
  ports:
    - 8080:80
